SCRAPE_REDDIT_CONFIG = [
    [
        "wallstreetbets",
        "stocks",
        "ocugen",
        "teslainvestorsclub",
        "SPACs",
        "Bogleheads",
        "Investing",
        "CryptoCurrency",
        "Bitcoin",
        "ethereum",
        "dogecoin",
    ],
    [
        "Weekend",
        "Analysis",
        "Daily",
        "Discussion",
        "Thread",
        "Mods",
    ],
    100,
]
